from pathlib import Path
from bs4 import BeautifulSoup
from fontTools.ttLib import TTFont
from PIL import Image
import re, html, zipfile, os

ROOT = Path(__file__).resolve().parent.parent
source_pages = {p: p.read_text(encoding='utf-8') for p in (ROOT/'pages').rglob('*.html')}
backup = Path.home()/'.codex'/'backups'/'eliel-poster-before-signature.zip'
backup.parent.mkdir(parents=True,exist_ok=True)
legacy_backup=ROOT/'tools'/'before-signature.zip'
if legacy_backup.exists() and not backup.exists(): legacy_backup.replace(backup)
if not backup.exists():
    with zipfile.ZipFile(backup, 'w', zipfile.ZIP_DEFLATED) as z:
        for p in [ROOT/'index.html', *source_pages]:
            z.write(p, p.relative_to(ROOT))
else:
    with zipfile.ZipFile(backup) as z:
        source_pages={ROOT/n:z.read(n).decode('utf-8') for n in z.namelist() if n.startswith('pages/')}
(ROOT/'assets/fonts').mkdir(exist_ok=True)
font_dir = Path(os.environ['LOCALAPPDATA'])/'Microsoft/Windows/Fonts'
for source, target in [('Anton-Regular.ttf','anton.woff2'),('Outfit-Regular.ttf','outfit.woff2')]:
    font = TTFont(font_dir/source)
    font.flavor = 'woff2'
    font.save(ROOT/'assets/fonts'/target)
for source, target in [('abraham-gogo.png','abraham.webp'),('master-class.png','masterclass.webp')]:
    im=Image.open(ROOT/'assets/img/portfolio'/source)
    im.save(ROOT/'assets/img/portfolio'/target, 'WEBP', quality=88)

def esc(v): return html.escape(str(v),quote=True)
def header(base):
    return f'''<a class="skip" href="#main">Aller au contenu</a><header class="site-header"><a class="brand" href="{base}index.html" aria-label="ELIEL POSTER, accueil"><img src="{base}assets/img/brand-mark.svg" width="22" height="30" alt=""><span>ELIEL<br>POSTER</span></a><nav id="navigation" class="header-links" aria-label="Navigation principale"><a href="{base}pages/portfolio.html">Les projets</a><a href="{base}index.html#studio">Le studio</a><a href="{base}index.html#atelier">L’atelier</a><a class="contact-nav" href="{base}pages/contact.html">Une idée en tête ? ↗</a></nav><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" type="button">Menu +</button></header>'''
def cta(base):
    return f'''<section class="contact-section" id="contact"><p class="eyebrow">La suite s’écrit ensemble.</p><a class="contact-title" href="{base}pages/devis.html">Faisons<br>impression. <span aria-hidden="true">↗</span></a><div class="contact-bottom"><p>Une marque à faire naître.<br>Une idée à faire grandir.</p><a class="text-link" href="mailto:postereliel@gmail.com">postereliel@gmail.com <span aria-hidden="true">↗</span></a></div></section>'''
def footer(base):
    return f'''<footer class="site-footer"><div class="footer-top"><a class="footer-brand" href="{base}index.html">ELIEL POSTER<br>Studio créatif indépendant.</a><nav class="footer-links" aria-label="Navigation complémentaire"><a href="{base}pages/grilletarif.html">Tarifs</a><a href="{base}pages/centre-information.html">Informations</a><a href="{base}pages/journal.html">Journal</a><a href="https://instagram.com/elielposter" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/company/eliel-poster/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://wa.me/2250576224680" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></nav></div><div class="footer-end"><span>© 2026 ELIEL POSTER</span><span>Du sens. Du caractère.</span><span>Abidjan, Côte d’Ivoire</span></div></footer>'''
def viewer():
    return '''<dialog class="viewer" id="viewer" aria-labelledby="viewer-title"><div class="viewer-bar"><p id="viewer-title">ELIEL POSTER</p><button class="viewer-close" type="button" aria-label="Fermer la présentation">Fermer ×</button></div><div class="viewer-media"></div><p class="viewer-copy"></p></dialog>'''
def shell(title,body,base='',cls='',description='ELIEL POSTER, studio créatif indépendant à Abidjan. Design graphique, identité visuelle, affiches et motion design.'):
    return f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#e12c25"><title>{esc(title)} — ELIEL POSTER</title><meta name="description" content="{esc(description)}"><meta property="og:title" content="{esc(title)} — ELIEL POSTER"><meta property="og:description" content="{esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="https://elielposter.com/assets/video/motion-studio-poster.webp"><link rel="icon" href="{base}favicon.svg" type="image/svg+xml"><link rel="preload" href="{base}assets/fonts/anton.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="{base}assets/css/signature.css"></head><body class="{cls}">{header(base)}<main id="main">{body}</main>{footer(base)}{viewer()}<script src="{base}assets/js/signature.js" defer></script></body></html>'''
def work(base='', heading=True):
    heading_html = '''<div class="section-heading"><div><p class="eyebrow">Une sélection du studio</p><h2>Le fond.<br>Et la forme.</h2></div><p>Un écran, une affiche, un film.<br>Trois façons de laisser une trace.</p></div>''' if heading else ''
    return f'''<section class="work" id="projets">{heading_html}<div class="work-grid"><article class="project reveal" id="projet-abraham"><a class="project-image web-art" href="{base}pages/project-abraham.html" aria-label="Découvrir le projet Abraham Dogo"><img src="{base}assets/img/portfolio/abraham.webp" width="1885" height="980" alt="Portfolio d’Abraham Dogo, Les mots justes, les idées folles" loading="lazy" decoding="async"></a><div class="project-meta"><div><h3><a href="{base}pages/project-abraham.html">Abraham Dogo</a></h3><p>Direction artistique · Web design</p></div><span>↗</span></div></article><article class="project reveal" id="projet-masterclass"><a class="project-image print-art" href="{base}pages/project-masterclass.html" aria-label="Découvrir le projet Master Class d’Adoration"><img src="{base}assets/img/portfolio/masterclass.webp" width="780" height="839" alt="Affiche Master Class d’Adoration pour Divine Production" loading="lazy" decoding="async"></a><div class="project-meta"><div><h3><a href="{base}pages/project-masterclass.html">Master Class d’Adoration</a></h3><p>Affiche · Communication visuelle</p></div><span>↗</span></div></article><article class="project reveal" id="projet-motion"><a class="project-image motion-art" href="{base}pages/project-motion.html" aria-label="Découvrir le film ELIEL POSTER"><img src="{base}assets/video/motion-studio-poster.webp" width="1280" height="720" alt="ELIEL POSTER, du mouvement : typographie cinétique rouge et crème" loading="lazy" decoding="async"></a><div class="project-meta"><div><h3><a href="{base}pages/project-motion.html">L’idée prend vie.</a></h3><p>ELIEL POSTER · Motion design</p></div><span>↗</span></div></article></div>{f'<div class="work-ending"><a class="text-link" href="{base}pages/portfolio.html">Explorer les projets <span aria-hidden="true">↗</span></a></div>' if heading else ''}</section>'''
def atelier(base=''):
    return f'''<section class="playground" id="atelier" aria-labelledby="atelier-title"><div class="play-copy"><p class="eyebrow">L’atelier ouvert</p><h2 id="atelier-title">À votre tour<br>de laisser<br>une trace.</h2><p>Un mot. Une couleur. Une intention.<br>Jouez avec notre matière première et composez votre affiche.</p><div class="play-controls"><span class="control-label" id="palette-label">Choisissez votre encre</span><div class="swatches" role="group" aria-labelledby="palette-label"><button class="swatch" type="button" style="--swatch:#e12c25" data-color="#e12c25" data-ink="#f1eee7" aria-label="Rouge signature" aria-pressed="true"></button><button class="swatch" type="button" style="--swatch:#20201e" data-color="#20201e" data-ink="#f1eee7" aria-label="Noir encre" aria-pressed="false"></button><button class="swatch" type="button" style="--swatch:#d4d8a7" data-color="#d4d8a7" data-ink="#20201e" aria-label="Vert papier" aria-pressed="false"></button><button class="swatch" type="button" style="--swatch:#c7b6df" data-color="#c7b6df" data-ink="#20201e" aria-label="Lilas" aria-pressed="false"></button></div><label class="control-label" for="poster-word">Votre mot, votre intention</label><input class="word-input" id="poster-word" type="text" value="Oser." maxlength="12" autocomplete="off" spellcheck="false"></div></div><div class="poster-composition" aria-label="Votre composition typographique"><div class="poster-top"><span>ELIEL POSTER</span><span>Atelier libre</span></div><div class="poster-type"><span data-poster-word>Oser.</span><span class="outline" data-poster-word>Oser.</span><span data-poster-word>Oser.</span></div><img class="poster-mark" src="{base}assets/img/brand-mark.svg" width="50" height="65" alt=""><div class="poster-foot"><span>Une idée prend forme.</span><span>EP®</span></div></div></section>'''

hero='''<section class="hero" aria-labelledby="hero-title"><div class="hero-top"><p>Studio indépendant<br>de création visuelle.</p><span>Le sens rencontre<br>le caractère.</span></div><h1 class="hero-title" id="hero-title"><span>Faire</span><span class="second"><b>impression.</b><a class="hero-window" href="assets/video/eliel-poster-motion.mp4" data-view="film" data-title="ELIEL POSTER — L’idée prend vie" aria-label="Voir le film ELIEL POSTER en grand"><video id="hero-reel" muted loop playsinline preload="metadata" poster="assets/video/motion-studio-poster.webp" width="1280" height="720" aria-label="Aperçu du film ELIEL POSTER, sans audio"><source src="assets/video/eliel-poster-motion.mp4" type="video/mp4"></video></a></span></h1><div class="hero-bottom"><p class="hero-statement">Nous donnons aux idées<br>une forme qu’on n’oublie pas.</p><div class="hero-actions"><button data-reel-toggle type="button" aria-controls="hero-reel" class="film-status">Lire l’aperçu</button><a class="film-trigger" href="assets/video/eliel-poster-motion.mp4" data-view="film"><span aria-hidden="true">↗</span><span>Le studio en mouvement</span></a><a class="round-link" href="#projets" aria-label="Découvrir nos projets">↓</a></div></div><div class="hero-rule"></div><div class="hero-foot"><span>ELIEL POSTER — Design & motion</span><span>Une présence. Une signature.</span></div></section>'''
studio='''<section class="studio" id="studio"><p class="eyebrow">Notre conviction</p><h2 class="studio-sentence reveal">On ne crée pas<br>pour remplir l’espace.<br>On crée pour <em>y laisser<br>quelque chose.</em></h2><div class="studio-bottom"><p>Une marque, c’est une façon d’être au monde. Nous lui donnons une voix visuelle : claire, singulière, cohérente. De la première esquisse au dernier mouvement.</p><div class="expertise"><details open><summary>Identité & branding</summary><p>Logo, charte graphique et direction artistique. Un langage visuel qui vous ressemble et vous distingue.</p></details><details><summary>Design graphique & affiches</summary><p>Des compositions qui font passer le message. Affiches, édition et visuels de communication, sur papier comme à l’écran.</p></details><details><summary>Motion design</summary><p>Typographie cinétique, animation et vidéo. Faire du mouvement une part entière de votre identité.</p></details><details><summary>Design digital</summary><p>Sites web et expériences intuitives. Donner à votre image une présence digitale précise et vivante.</p></details><a class="text-link" href="pages/method.html">De l’idée à la réalisation <span aria-hidden="true">↗</span></a></div></div></section>'''
(ROOT/'index.html').write_text(shell('Faire impression',hero+work()+studio+atelier()+cta(''),cls='home'),encoding='utf-8')

def pagehero(label,title,intro='',cls=''):
    return f'<section class="page-hero {cls}"><p class="eyebrow">{label}</p><h1>{title}</h1>{f"<p class=\"intro\">{intro}</p>" if intro else ""}</section>'
def save(name,title,body,cls=''):
    (ROOT/'pages'/name).write_text(shell(title,body,'../',cls),encoding='utf-8')
save('portfolio.html','Les projets',pagehero('Le travail parle.','Matière<br>à regarder.','Un site. Une affiche. Un film.<br>À chaque projet, sa propre expression.')+work('../',False)+cta('../'),'portfolio-page')
save('project-abraham.html','Abraham Dogo',pagehero('Direction artistique · Web design','Les mots justes.<br>Les idées folles.')+'''<section class="case"><div class="case-layout"><div class="case-art" style="background:#d4d8a7"><img src="../assets/img/portfolio/abraham.webp" width="1885" height="980" alt="Page d’accueil du portfolio d’Abraham Dogo"></div><div class="case-copy"><p class="eyebrow">Abraham Dogo</p><h2>Faire une place<br>aux idées.</h2><p>Conception et développement d’un portfolio pour donner toute leur place aux mots, aux idées et au travail d’Abraham Dogo.</p><p>La typographie devient le premier point de rencontre. Une composition directe, pensée pour laisser le travail de conception-rédaction s’exprimer.</p><dl class="case-facts"><div><dt>Format</dt><dd>Portfolio digital</dd></div><div><dt>Intervention</dt><dd>Design & développement</dd></div></dl><a class="text-link" href="https://abrahamdogo.netlify.app/" target="_blank" rel="noopener noreferrer">Explorer le site <span aria-hidden="true">↗</span></a></div></div></section>'''+cta('../'))
save('project-masterclass.html','Master Class d’Adoration',pagehero('Affiche · Communication visuelle','Une voix.<br>Une image.')+'''<section class="case"><div class="case-layout"><div class="case-art"><a href="../assets/img/portfolio/master-class.png" data-view="image" data-title="Master Class d’Adoration — Divine Production" aria-label="Agrandir l’affiche"><img src="../assets/img/portfolio/masterclass.webp" width="780" height="839" alt="Master Class d’Adoration, affiche événementielle Divine Production"></a></div><div class="case-copy"><p class="eyebrow">Divine Production</p><h2>Donner une présence<br>à la rencontre.</h2><p>Une affiche événementielle pour la Master Class d’Adoration du 2 avril 2026. Une composition qui réunit les intervenants et rend les informations de la rencontre immédiatement repérables.</p><dl class="case-facts"><div><dt>Support</dt><dd>Affiche événementielle</dd></div><div><dt>Intervention</dt><dd>Direction artistique & design graphique</dd></div></dl><a class="text-link" href="../assets/img/portfolio/master-class.png" data-view="image" data-title="Master Class d’Adoration">Voir l’affiche en grand <span aria-hidden="true">↗</span></a></div></div></section>'''+cta('../'))
save('project-motion.html','L’idée prend vie',pagehero('ELIEL POSTER · Motion design','L’idée<br>prend vie.')+'''<section class="reel-page"><video controls playsinline preload="metadata" poster="../assets/video/motion-studio-poster.webp" width="1280" height="720" aria-label="Film ELIEL POSTER, douze secondes sans audio" aria-describedby="film-transcript"><source src="../assets/video/eliel-poster-motion.mp4" type="video/mp4"><a href="../assets/video/eliel-poster-motion.mp4">Télécharger le film</a></video></section><div class="film-description"><p>Une création originale du studio. Typographie cinétique, formes graphiques et transitions : notre identité prend vie en douze secondes.</p><div><details id="film-transcript"><summary>Lire le film en texte</summary><p>Une idée. Prend forme. Du mouvement. ELIEL POSTER : votre image, une autre dimension.</p></details><a class="text-link" href="../assets/video/eliel-poster-motion.mp4" download>Télécharger le film <span aria-hidden="true">↓</span></a></div></div>'''+cta('../'))
form='''<section class="inquiry"><div class="contact-address"><p>Tout commence par un échange.<br>Racontez-nous ce que vous avez en tête.</p><a href="mailto:postereliel@gmail.com">postereliel@gmail.com ↗</a><a href="tel:+2250576224680">+225 05 76 22 46 80 ↗</a><a class="text-link" href="https://wa.me/2250576224680" target="_blank" rel="noopener noreferrer">Échanger sur WhatsApp ↗</a><p>Abidjan, Côte d’Ivoire</p><a class="text-link" href="grilletarif.html">Consulter les tarifs ↗</a></div><form class="brief-form"><div class="field"><label for="brief-name">Votre nom *</label><input id="brief-name" name="name" required autocomplete="name" maxlength="100"></div><div class="field"><label for="brief-email">Votre email *</label><input id="brief-email" name="email" type="email" required autocomplete="email" maxlength="150"></div><div class="field"><label for="brief-service">Votre projet</label><select id="brief-service" name="service"><option>Identité & branding</option><option>Design graphique & affiche</option><option>Motion design</option><option>Site web</option><option>À définir ensemble</option></select></div><div class="field"><label for="brief-budget">Votre budget</label><select id="brief-budget" name="budget"><option>À définir ensemble</option><option>Moins de 100 000 FCFA</option><option>100 000 à 300 000 FCFA</option><option>300 000 à 500 000 FCFA</option><option>Plus de 500 000 FCFA</option></select></div><div class="field full"><label for="brief-message">Parlez-nous de votre idée *</label><textarea id="brief-message" name="message" required maxlength="4000" placeholder="Votre projet, vos envies, votre calendrier…"></textarea></div><div class="form-action"><button class="submit" type="submit">Préparer mon message <span aria-hidden="true">↗</span></button><small>Le formulaire prépare votre message. Vous choisissez ensuite de l’envoyer par email ou WhatsApp.</small></div><div class="form-status" role="status" tabindex="-1" aria-live="polite"></div></form></section>'''
save('contact.html','Parlons de votre idée',pagehero('À vous de jouer.','La prochaine<br>impression.<br>C’est la vôtre.')+form)
save('devis.html','Votre projet',pagehero('De l’intention à la création.','Une idée<br>en tête ?')+form)
save('lab.html','L’atelier',pagehero('Expérimenter, c’est chercher.','Le droit<br>d’essayer.')+atelier('../')+cta('../'))

# Rebuild secondary routes with their genuine editorial content; old layout and scripts are discarded.
handled={'portfolio.html','contact.html','devis.html','lab.html'}
for path, original in source_pages.items():
    if path.name in handled and path.parent.name=='pages': continue
    soup=BeautifulSoup(original,'html.parser')
    title_node=soup.find('h1')
    title=title_node.get_text(' ',strip=True) if title_node else path.stem.replace('-',' ').capitalize()
    content=soup.find('main')
    if content is None:
        content=soup.find('body')
    if content is None: continue
    for node in content.select('script,style,header,footer,nav,dialog,form,h1,button,.skip-link,.back-to-top'):
        node.decompose()
    for node in list(content.find_all(True)):
        if node.attrs is None: continue
        if node.name in ('svg','video','img','source','iframe'):
            node.decompose(); continue
        keep={k:v for k,v in node.attrs.items() if k in ('href','id','colspan','rowspan','open')}
        node.attrs=keep
        if node.name in ('div','section','article','span') and not node.get('id'):
            node.unwrap()
    base='../../' if path.parent.name=='explorations' else '../'
    body=pagehero('Le regard du studio',esc(title))+f'<article class="editorial">{content.decode_contents()}</article>'+cta(base)
    path.write_text(shell(title,body,base),encoding='utf-8')

print(f'Rebuilt homepage, projects, contact, atelier and {len(source_pages)-len(handled)} editorial routes.')
for p in [ROOT/'assets/css/signature.css',ROOT/'index.html',*(ROOT/'pages').rglob('*.html')]:
    result=p.read_text(encoding='utf-8').replace('#e12c25','#ce2923')
    if p.suffix=='.html':
        relative=p.relative_to(ROOT).as_posix()
        canonical='https://elielposter.com/'+('' if relative=='index.html' else relative)
        result=result.replace('</head>',f'<link rel="canonical" href="{canonical}"></head>')
        result=result.replace('id="hero-title"','id="hero-title" aria-label="Faire impression."')
    p.write_text(result,encoding='utf-8')
